### ISSUE TITLE
How is PartNum used by UDFInitAllocationCache?

### ISSUE THREAD

**Issue by Zero3K** [Zero3K/udfs#1]
*subject*

**Comment by Alter-1** [comment]
Partnum in code is used as index inside list of partitions.
But code is written with assumption that PartNum (just index in list) == ParRefNum (id used in UDF structures).
So, PartNum from on-disk structure must be mapped into driver internal index on mount. And translated back when writin on-disk structures.
AllocationCache in original version supported only free space bitmap. But new UDF version may use (and actually use) allocation space extents, those must be recognized on mount (easy) and reconstructed/rewritten on dismount (a bit complicated, since may need reallocation)

**Comment by mann3616** [comment]
And what about the file descCRCLength/other tag information being wrong? Mostly when creating file this occurs.

**Comment by Zero3K** [comment]
The block size is 512.

**Comment by Alter-1** [comment]
logical == physical ? Ok, we used it by default too. I've  checked now

**Comment by Zero3K** [comment]
What do you mean by incorrect input?

**Comment by Alter-1** [comment]
for function which calculates CRC. Or block is chenged between CRC update and writing to disk.
Did you inspect content of broken descriptor ?

**Comment by mann3616** [comment]
I agree I think it's overwriting, I was really beginning to question why it was running UDFSetUpTag on the same locs so many times. Which means I need to rewrite and deconstruct on dismount for those Extents. We have a dumpinfo tool that allows us to see what is broken on the descriptor.

**Comment by Alter-1** [comment]
2.50 free space tracking model is really tricky. Yes, you should completly reconstruct allocated space extent. May be you will also need to reserve some space in run-time for this extent since it may become larger. It will take too much time to do it after each allocation, but it is possible to invent some condition, for example only when we have less than 3% of free space left ( 512 byte block may contain up to N = (512 - tagged header size) / 8 extents ) and when this limit is reached, recalculate its size each N allocation attempts

**Comment by Alter-1** [comment]
Then its rather strange. The main difference that I can see for now is 8192 partition reference instead of 0
2.01 use free space bitmap of fixed size.
I can imagine that it is handled incorrectly (without mapping in all places) and on dismount we get translate all addresses (lba + partnum) into 0 + some partition start offset and write everything in the same place

**Comment by mann3616** [comment]
The part num is being mapped in all places. There is UNALLOC_SPACE_DESC which I think maybe that is what you are talking about earlier where these must be reconstructed/rewritten?

**Comment by mann3616** [comment]
I definitely think that you were saying about the extents is true because Recycled FE is located at 1a0 and one of the UNALLOC_SPACE_DESC is at 1b0, which means that the file Recycled is overwriting the unalloc_space_desc stuff, which in turn causes the CRC information to be incorrect.

**Comment by Alter-1** [comment]
in general, unalloc_space_desc and Recycled is not necessary for HDD storage, it is used on CD media to avoid too frequent use of the same locations. But if it is already there, then it should be correctly reconstructed and probably reallocated according to changed layout.

**Comment by Zero3K** [comment]
https://devblogs.microsoft.com/oldnewthing/20060131-00/?p=32453

**Comment by mann3616** [comment]
[udf.log](https://github.com/Zero3K/udfs/files/11066875/udf.log)
Here is the log file: I would like confirmation that the overwriting is not in my head lol.  Location in question is under UDFBuildFreeSpaceBitmap where we have multiple Extents that are found at different lba logical the one i am worried about is 0x1b0. Later we are Setting up tags for Root directory EFE along with other FE but the root directory EFE is located at logical lba 0x1a0. Which is what leads me to believe that the Extent at 1b0 is getting overwritten which in turn is calculating the incorrect CRC. But that is my opinion, and a lot happens to the same logical lba so I would love to get your opinion as well. @Alter-1

**Comment by Zero3K** [comment]
Still no response from @Alter-1.

**Comment by Zero3K** [comment]
Is there a program that could tell us what the last possible lba is?

**Comment by Zero3K** [comment]
Are these values the location and size of unallocated space? If so, then they overlap a lot

![image](https://user-images.githubusercontent.com/6194332/228348121-d0d351ad-abfb-4a1c-a900-2d9400c53b1d.png)

**Comment by Alter-1** [comment]
Last possible LBA is reported by storage driver on mount. It is used to find secondary anchor descriptor

**Comment by Zero3K** [comment]
> Is it valid descriptor with valid tag and CRC ? Sequence number 4 is too suspicious, since we had only 8192 in partition list. Who have produced it ?

Windows 7/Windows 10

**Comment by mann3616** [comment]
LastPossibleLba is something curious because the unallocated space descriptors have their location turned into physical lba and it fails the out of bounds check against LastPossibleLba. Turns out that because it is marking unallocated space even past the LastPossibleLba since the partition ends before the actual last lba on disk.
Here is some dump info on the corrupted VHD: (Note: that the descCRClength is exactly the FileSize away from being correct, if I correct this then the descCRC computation is off)
[udf2-0-1.log](https://github.com/Zero3K/udfs/files/11093769/udf2-0-1.log)

**Comment by Zero3K** [comment]
or find out which SetTag is messing it up

SetTag Loc=1a0(0), tagIdent=101, skip=0

sometimes 1a0 in parenthesis is becoming 0

and tagIdent is changing from 105 to 101

no other loc is being zeroed

maybe that explains things

do you agree?

What do the numbers represent?

the one in parentheses and the tagIdent number

**Comment by mann3616** [comment]
in the parentheses is the location the tag currently has and out of the parentheses is the location that we want to update it with. 101 is TID_FILE_IDENT_DESC and 105 is TID_FILE_ENTRY

**Comment by Zero3K** [comment]
This question has been answered and is no longer needing to be open.
